spring:
  application:
    name: EDU-VIDEO
  servlet:
    # 最大上传单个文件大小：默认1M
    multipart.max-file-size: 1024MB
    # 最大置总上传的数据大小 ：默认10M
    multipart.max-request-size: 1024MB
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8888/eureka/
#  instance:
#    appname: EDU-VIDEO
#    prefer-ip-address: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8002
oss:
  accessKeyId: LTAI4GL9bFTevrU3NhT6LZ6V
  accessKeySecret: 13SIyyaUWAuEvNgyNjQtyhi7REO2uI